/*
 * This source file was generated by the Gradle 'init' task
 */
package edu.curso;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test
    public void testeInstanciaFuncionario(){
        //Testa se a classe Funcionario pode ser criada e se os dados batem
        Funcionario f = new Funcionario();
        f.setNome("Gustavo");
        f.setMatricula("123-X");
        f.setSalario(5000.0f);

        assertNotNull( "O funcionario deve ser instanciado", f);
        assertEquals("Gustavo", f.getNome());
        assertEquals("123-X", f.getMatricula());
        assertEquals(5000.0f, f.getSalario(), 0);
    }
}
